### ISSUE TITLE
Guidance on using configuration in Github Actions

### ISSUE THREAD

**Issue by v2kiran** [PowershellFrameworkCollective/psframework#593]
Hi 
i am trying to use the config system in github actions but struglling to understand soem things. The config-test.json is placed within the ps directory.
code used to generate the config:

```ps
# Gather settings to export
$configToExport = @()
$configToExport += Set-PSFConfig -FullName "MyProject.Build.Repository" -Value "foo" -SimpleExport -PassThru
$configToExport += Set-PSFConfig -FullName "MyProject.Build.Artifactory" -Value "bar" -SimpleExport -PassThru
$configToExport += Set-PSFConfig -FullName "SomeModule.SomeSetting" -Value "1" -SimpleExport -PassThru
$configToExport += Set-PSFConfig -FullName "SomeModule.SomeSetting2" -Value 2 -SimpleExport -PassThru
$configToExport += Set-PSFConfig -FullName "SomeModule2.SomeSetting" -Value "3" -SimpleExport -PassThru
$configToExport += Set-PSFConfig -FullName "SomeModule2.SomeSetting2" -Value $true -SimpleExport -PassThru

# Write the configuration file
$configToExport | Export-PSFConfig -OutPath .\config-test.json
```

Want to use the config above in the workflow below:

```yaml

  job_1:
    name: "Create Keys"
    runs-on: ubuntu-latest
    environment: tfplan
    steps:
      - uses: actions/checkout@v2

      - name: PowerShell Script - Import psfconfig
        run: |
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
          install-module psframework
          import-psfconfig -path ps/config-test.json | Register-PSFConfig -Scope SystemDefault
          get-psfconfig
          Get-PSFConfigValue -FullName MyProject.Build.Repository
        shell: pwsh

      - name: PowerShell Script - test imported value
        run: |
          get-psfconfig
          Get-PSFConfigValue -FullName MyProject.Build.Artifactory | Write-Verbose -Verbose
          Get-PSFConfigValue -FullName MyProject.Build.Repository | Write-Verbose -Verbose
        shell: pwsh

  job_2:
    runs-on: ubuntu-latest
    name:  Encryption Keys
    needs: [job_1]
    environment: tfplan
    steps:
      - uses: actions/checkout@v2

      - name: PowerShell Script
        run: |
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
          install-module psframework
          Get-PSFConfigValue -FullName MyProject.Build.Artifactory
        shell: pwsh

```

The config imported and registered in step 1 is not available in step 2 (PowerShell Script - test imported value)
Also is it correct to expect that the config will be available in job_2 ? Do i need to re-import or re-register?
